# VIA_ENABLE = yes # TODO: gives error

# START TAP DANCE
TAP_DANCE_ENABLE = yes
UNICODE_ENABLE = yes
# END TAP DANCE

# START HOME ROW MODS
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes # also needed for custom heatmap
# END HOME ROW MODS